### ISSUE TITLE
[archlan/iso]Can't build ISO

### ISSUE THREAD

**Issue by alannxq** [archlan/issue-tracker#22]
Running,
```
sudo ./mkarchiso -v "."
```
gives the error: 
```
error: no usable package repositories configured.
==> ERROR: Failed to install packages to new root
```

**Comment by Lanhild** [comment]
If possible, I would like to get more lines of logs to understand why it happened. Otherwise, please retry since this **supposedly can't** happen.

**Comment by Lanhild** [comment]
My mistake, still learning, hehe. Fixing it right now and updating the release. Should work if you retry now.
